[tox]
envlist =
  python3.6, python3.7, python3.8, python3.9, python3.10, flake8, Cython

[gh-actions]
python =
  3.6: python3.6, flake8
  3.7: python3.7
  3.8: python3.8
  3.9: python3.9
  3.10: python3.10


[testenv]
setenv =
  PYTHONPATH = {toxinidir}
deps =
  -r {toxinidir}/requirements.txt
commands =
  python3 -m pytest test/

[flake8]
max-line-length = 88
extend-ignore = E203,E402
commands = flake8 .
